In [2]:
%pip install tensorflow

Collecting tensorflow
  Using cached tensorflow-2.21.0-cp311-cp311-win_amd64.whl (350.8 MB)
Collecting absl-py>=1.0.0
  Using cached absl_py-2.4.0-py3-none-any.whl (135 kB)
Collecting astunparse>=1.6.0
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\python311\lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\python311\lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\python311\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\python311\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\python311\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\malak\appdata\roaming\python\python311\site-packages (from tensorflow) (26.1)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\python311\lib\site-packages (from tensorflow) (7.34.1)
Collecting requests<3,>=2.21.0
  Using cached requests-2.33.1-py3-none-any.whl (64 kB)
Requirement already satisfied: setuptools in c:\python311\lib\site-packages (from tensorflow) (65.5.0)
Requirement already satisfied: six>=1.12.0 in c:\users\malak\appdata\roaming\python\python311\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\python311\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\malak\appdata\roaming\python\python311\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\python311\lib\site-packages (from tensorflow) (2.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\python311\lib\site-packages (from tensorflow) (1.80.0)
Collecting keras>=3.12.0
  Using cached keras-3.14.0-py3-none-any.whl (1.6 MB)
Requirement already satisfied: numpy>=1.26.0 in c:\python311\lib\site-packages (from tensorflow) (2.4.4)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\python311\lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\python311\lib\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\python311\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.46.3)
Collecting rich
  Using cached rich-15.0.0-py3-none-any.whl (310 kB)
Requirement already satisfied: namex in c:\python311\lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\python311\lib\site-packages (from keras>=3.12.0->tensorflow) (0.19.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\python311\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\python311\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in c:\python311\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.6.3)
Collecting certifi>=2023.5.7
  Using cached certifi-2026.2.25-py3-none-any.whl (153 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\python311\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\malak\appdata\roaming\python\python311\site-packages (from rich->keras>=3.12.0->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\python311\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Installing collected packages: certifi, absl-py, rich, requests, astunparse, keras, tensorflow
Note: you may need to restart the kernel to use updated packages.

  WARNING: Failed to write executable - trying to use .deleteme logic
ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'c:\\Python311\\Scripts\\saved_model_cli.exe' -> 'c:\\Python311\\Scripts\\saved_model_cli.exe.deleteme'


[notice] A new release of pip available: 22.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import tensorflow as tf

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('all_tickets_processed_improved_v3.csv')

In [6]:
df.head()

                                            Document    Topic_group
0  connection with icon icon dear please setup ic...       Hardware
1  work experience user work experience user hi w...         Access
2  requesting for meeting requesting meeting hi p...       Hardware
3  reset passwords for external accounts re expir...         Access
4  mail verification warning hi has got attached ...  Miscellaneous

In [7]:
print(df.columns)

Index(['Document', 'Topic_group'], dtype='str')

In [8]:
df.dropna()

                                                Document    Topic_group
0      connection with icon icon dear please setup ic...       Hardware
1      work experience user work experience user hi w...         Access
2      requesting for meeting requesting meeting hi p...       Hardware
3      reset passwords for external accounts re expir...         Access
4      mail verification warning hi has got attached ...  Miscellaneous
...                                                  ...            ...
47832  git space for a project issues with adding use...         Access
47833  error sent july error hi guys can you help out...  Miscellaneous
47834  connection issues sent tuesday july connection...       Hardware
47835  error cube reports sent tuesday july error hel...     HR Support
47836  running out on extensions hello please be advi...       Hardware

[47837 rows x 2 columns]

In [9]:
texts=df["Document"]
labels=df["Topic_group"]

In [10]:
import re
def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text) # Remove punctuation/special chars
    return text

In [11]:
df["clean_text"] = df["Document"].apply(clean_text)

texts = df["clean_text"]

In [12]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [13]:
Tokenizer=Tokenizer(num_words=10000, oov_token="<OOV>")
Tokenizer.fit_on_texts(texts)

In [15]:
sequences = Tokenizer.texts_to_sequences(texts)

In [16]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

max_len = 100

X = pad_sequences(sequences, maxlen=max_len, padding='post')

In [20]:
%pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp311-cp311-win_amd64.whl (8.1 MB)
     ---------------------------------------- 8.1/8.1 MB 922.5 kB/s eta 0:00:00
Requirement already satisfied: numpy>=1.24.1 in c:\python311\lib\site-packages (from scikit-learn) (2.4.4)
Collecting scipy>=1.10.0
  Downloading scipy-1.17.1-cp311-cp311-win_amd64.whl (36.6 MB)
     -------------------------------------- 36.6/36.6 MB 690.6 kB/s eta 0:00:00
Collecting joblib>=1.3.0
  Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Collecting threadpoolctl>=3.2.0
  Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.5.3 scikit-learn-1.8.0 scipy-1.17.1 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [21]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(labels)

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [25]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

In [34]:
rnn_model = Sequential([
    Embedding(input_dim=10000, output_dim=64, input_length=100),
    SimpleRNN(64),
    Dense(32, activation='relu'),
    Dense(8, activation='softmax')
])

c:\Python311\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [35]:
rnn_model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [36]:
print(df.columns)
print(len(set(y)))
print(X.shape)

Index(['Document', 'Topic_group', 'clean_text'], dtype='str')
8
(47837, 100)

In [39]:
rnn_model.fit(X_train, y_train, epochs=10, batch_size=32)

Epoch 1/10
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 47s 39ms/step - accuracy: 0.3224 - loss: 1.7219
Epoch 2/10
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 48s 40ms/step - accuracy: 0.3255 - loss: 1.7128
Epoch 3/10
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.3279 - loss: 1.7054
Epoch 4/10
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 86s 39ms/step - accuracy: 0.3288 - loss: 1.7011
Epoch 5/10
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 46s 38ms/step - accuracy: 0.3291 - loss: 1.7001
Epoch 6/10
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 43s 36ms/step - accuracy: 0.3300 - loss: 1.6962
Epoch 7/10
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 38s 32ms/step - accuracy: 0.3313 - loss: 1.6920
Epoch 8/10
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 36s 30ms/step - accuracy: 0.3307 - loss: 1.6897
Epoch 9/10
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 39s 32ms/step - accuracy: 0.3326 - loss: 1.6887
Epoch 10/10
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 39s 33ms/step - accuracy: 0.3331 - loss: 1.6864

In [40]:
rnn_model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [41]:
from sklearn.metrics import classification_report

y_pred = rnn_model.predict(X_test)
y_pred = y_pred.argmax(axis=1)

print(classification_report(y_test, y_pred))

299/299 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step
              precision    recall  f1-score   support

           0       0.24      0.02      0.04      1455
           1       0.50      0.09      0.15       342
           2       0.58      0.07      0.12      2107
           3       0.29      0.92      0.44      2760
           4       0.18      0.02      0.03       451
           5       0.30      0.03      0.06      1400
           6       0.09      0.00      0.00       497
           7       0.11      0.01      0.02       556

    accuracy                           0.29      9568
   macro avg       0.28      0.14      0.11      9568
weighted avg       0.33      0.29      0.17      9568

In [43]:
from tensorflow.keras.layers import LSTM

lstm_model = Sequential([
    Embedding(input_dim=10000, output_dim=64, input_length=max_len),
    LSTM(64),
    Dense(32, activation='relu'),
    Dense(8, activation='softmax')
])

In [44]:
lstm_model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

lstm_model.fit(X_train, y_train, epochs=5, batch_size=32)

Epoch 1/5
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 96s 77ms/step - accuracy: 0.3120 - loss: 1.7974
Epoch 2/5
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 75s 62ms/step - accuracy: 0.3489 - loss: 1.7439
Epoch 3/5
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 76s 64ms/step - accuracy: 0.4870 - loss: 1.4073
Epoch 4/5
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 79s 66ms/step - accuracy: 0.6535 - loss: 0.9893
Epoch 5/5
1196/1196 ━━━━━━━━━━━━━━━━━━━━ 79s 66ms/step - accuracy: 0.7709 - loss: 0.6823

In [47]:
y_pred_lstm = lstm_model.predict(X_test)
y_pred_lstm = y_pred_lstm.argmax(axis=1)

lstm_accuracy=print(classification_report(y_test, y_pred_lstm))

299/299 ━━━━━━━━━━━━━━━━━━━━ 6s 20ms/step
              precision    recall  f1-score   support

           0       0.79      0.88      0.83      1455
           1       0.63      0.57      0.60       342
           2       0.81      0.85      0.83      2107
           3       0.77      0.86      0.81      2760
           4       0.77      0.59      0.67       451
           5       0.66      0.60      0.63      1400
           6       0.96      0.78      0.86       497
           7       0.92      0.57      0.70       556

    accuracy                           0.78      9568
   macro avg       0.79      0.71      0.74      9568
weighted avg       0.78      0.78      0.77      9568

In [46]:
lstm_model.save("lstm_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [54]:
# the LSTM model is better than the RNN model at least with 2 multoplay accuracy
# with half of epochs thanks to the memory skills of LSTM.
print (f"LSTM Accuracy:\n {classification_report(y_test, y_pred_lstm)} VS.\n RNN Accuracy:\n {classification_report(y_test, y_pred)}")

LSTM Accuracy:
               precision    recall  f1-score   support

           0       0.79      0.88      0.83      1455
           1       0.63      0.57      0.60       342
           2       0.81      0.85      0.83      2107
           3       0.77      0.86      0.81      2760
           4       0.77      0.59      0.67       451
           5       0.66      0.60      0.63      1400
           6       0.96      0.78      0.86       497
           7       0.92      0.57      0.70       556

    accuracy                           0.78      9568
   macro avg       0.79      0.71      0.74      9568
weighted avg       0.78      0.78      0.77      9568
 VS.
 RNN Accuracy:
               precision    recall  f1-score   support

           0       0.24      0.02      0.04      1455
           1       0.50      0.09      0.15       342
           2       0.58      0.07      0.12      2107
           3       0.29      0.92      0.44      2760
           4       0.18      0.02      0.03       451
           5       0.30      0.03      0.06      1400
           6       0.09      0.00      0.00       497
           7       0.11      0.01      0.02       556

    accuracy                           0.29      9568
   macro avg       0.28      0.14      0.11      9568
weighted avg       0.33      0.29      0.17      9568